name: Build and Deploy to Azure Function App

on:
  push:
    branches:
      - main  # replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        npm install

    - name: 'Run Tests'
      shell: bash
      run: |
        npm run test  # replace with your test command

    - name: 'Deploy to Azure Functions'
      uses: azure/functions-action@v1
      id: fa
      with:
        app-name: Test-For-Function-Apps  # replace with your Function App name
        package: .
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  # set this in your repository secrets
